meetup_events_homepage:
    path:     /
    defaults: { _controller: MeetupEventsBundle:Default:index }

meetup_events_test:
    path:     /test
    defaults: { _controller: MeetupEventsBundle:Default:test }

meetup_event:
    path:     /event/{groupUrl}/{eventId}
    defaults: { _controller: MeetupEventsBundle:Default:event }